backend:
  name: github
  repo: developerjahid/creative-blog

media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: static/assets/blog
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime, required: true }
      - { name: title, label: Title, widget: string, required: true }
      - { name: tags, label: Tags,  widget: list, default: ["news, netlify, hwlo"], required: true }
      - { name: keywords, label: SEO keywords, widget: text, required: true }
      - { name: description, label: SEO description, widget: text, required: true }
      - { name: image, label: Cover,  widget: image, required: true }
      - { name: body, label: Body, widget: markdown, required: true } 